//Employees
export const GET_EMPLOYEE_DETAILS = "GET_EMPLOYEE_DETAILS";
export const GET_EMPLOYEES_DETAILS_SUCCESS = "GET_EMPLOYEES_DETAILS_SUCCESS";
export const GET_EMPLOYEES_DETAILS_ERROR = "GET_EMPLOYEES_DETAILS_ERROR";

//Soft Deleted Employees
export const GET_SOFT_DELETED_EMPS = "GET_SOFT_DELETED_EMPS";
export const GET_SOFT_DELETED_EMPS_SUCCESS = "GET_SOFT_DELETED_EMPS_SUCCESS";
export const GET_SOFT_DELETED_EMPS_ERROR = "GET_SOFT_DELETED_EMPS_ERROR";